[package]
name = "histogrammer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndhistogram = "0.8.0"
humantime = "2.1.0"
tempfile  = "3.3.0"    # For tests that create ring item files.
libm = "0.2.6"

