[package]
name = "rustogramer"
version = "0.1.0"
edition = "2021"

[[bin]]
name="rustogrammer"
path="src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndhistogram = "0.9.0"
humantime = "2.1.0"
tempfile  = "3.5.0"    # For tests that create ring item files.
libm = "0.2.6"
glob = "0.3.1"
memmap = "0.6.2"
dirs = "5.0.0"
clap = { version = "4.2.7", features = ["derive"] }
portman_client="0.2.0"
serde = {version = "1.0.162", features = ["derive"]}
chrono="0.4.24"

[dependencies.rocket]
version="0.5.0-rc.3"
features=["json"]
